version: '3.8'

services:
  php:
      image: php:8.0-apache
      build:
        context: .
        dockerfile: Dockerfile
      container_name: sharing_php
      restart: always
      ports:
        - 80:80
      volumes:
        - ./public:/var/www/html

  db:
    image: mysql:5.7
    container_name: sharing_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_DATABASE=sharing
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: sharing_phpmyadmin
    restart: always
    ports:
      - 8080:80

volumes:
  db_data:
